---
title: "STATS 201 Lab Class 2"
author: 'LiYuzhuo-2019210146'
output:
  word_document: default
  pdf_document: default
---
\large

#Haemoglobin levels in athletes

# Code and output

```{r}
library(s20x)
## Loading in the data.
athletes.df = read.csv(file = "athletes.csv", header = TRUE)
athletes.df$Sex = factor(athletes.df$Sex)
## Plot the data.
pairs20x(athletes.df[,c(1, 3, 4, 5)])
pairs20x(athletes.df[,c(1, 2)])

hconc.fit = lm(Hconc ~ LBM, data = athletes.df)
plot(hconc.fit, which = 1)
normcheck(hconc.fit)
cooks20x(hconc.fit)
summary(hconc.fit)


hconc.fit2 = lm(Hconc ~ LBM + Weight, data = athletes.df)
plot(hconc.fit2, which = 1)
normcheck(hconc.fit2)
cooks20x(hconc.fit2)
summary(hconc.fit2)

pairs20x(athletes.df[,c(3, 4, 5)])

hconc.fit3 = lm(Hconc ~ LBM + Height, data = athletes.df)
summary(hconc.fit3)

hconc.fit4 = lm(Hconc ~ LBM + Height + Sex, data = athletes.df)
plot(hconc.fit4, which = 1)
normcheck(hconc.fit4)
cooks20x(hconc.fit4)
summary(hconc.fit4)

confint(hconc.fit4)

predict(hconc.fit4, data.frame("Sex"="M", "Height"=170, "Weight"=70, "LBM"=60), interval = "prediction")

predict(hconc.fit4, data.frame("Sex"="F", "Height"=170, "Weight"=70, "LBM"=60), interval = "prediction")





hconc.fit5 = lm(Hconc ~ Height * Sex, data = athletes.df)
summary(hconc.fit5)
#predict(hconc.fit5, data.frame("Sex"="M", "Height"=170, "Weight"=70, "LBM"=60), interval = "prediction")
#predict(hconc.fit5, data.frame("Sex"="F", "Height"=170, "Weight"=70, "LBM"=60), interval = "prediction")
#preds.df = data.frame("Sex"="M", "Height"=170, "Weight"=70, "LBM"=60), interval = "prediction")
#predict(hconc.fit4, preds, interval = "prediction")
##plot(Hconc ~ Sex, data = athletes.df)
##hconc.fit = lm(Hconc ~ Sex, data = athletes.df)
##cooks20x(hconc.fit)

## INSERT CODE HERE.
## Analyse the data.
## INSERT CODE HERE.
```

# Methods and Assumption Checks

From the pairs plot, we can concluded that Hconc was related to a number of our explanatory variables. So, we want to construct a multiple linear regression model with Hconc as the response variable.

We only use one parameter--LBM as explanatory variable at first, and all assumptions appear to be satisfied. Then we introduce Weight as another explanatory variable. But from the pairs plot, we saw that there is a strong correlation between Weight and LBM, so we shelved the case of introducing Weight as an explanatory variable. As we introduce Height and Sex, the Adjusted R-squared continuously increasing, so we keep them in our final model.

Our fimal model is:
  $Hconc_i = \beta_0 + \beta_1 \times LBM_i + \beta_2 \times Height_i + \beta_3 \times Sex_i + \epsilon_{i}$ where $Sex_i = 0$ if the athlete is female and 1 if the athlete is male, and $\epsilon_i \sim iid ~N(0,\sigma^2)$
  
Our model explains about 54.38% of the variability in Haemoglobin concentration in blood.

# Executive Summary

We are interested in build a model to explain  the Haemoglobin concentration in blood of athletes with their sex, height, weight, and LBM.

We can concluded from our analysis that:
  The mean of the Haemoglobin concentration in blood is between 17.62 and 25.58 grams per decalitre.
  We estimated that for each additional kg of athlete's LBM, the Haemoglobin concentration in blood increases by 0.02 to 0.069 grams per decalitre.
  We estimated that for each additional cm of athlete's Height, the Haemoglobin concentration in blood decreases by 0.03 to 0.08 grams per decalitre.
  And the predict value of haemoglobin concentration levels for a male with height 170 cm, weight 70kg, and lean body mass 60 kg is between 14.02 and 17.62 grams per decalitre.
  The predict value of haemoglobin concentration levels for a female with height 170 cm, weight 70kg, and lean body mass 60 kg is between 12.66 and 16.20 grams per decalitre.
  
When we fitted a model use Height and Sex as explanatory variable, as we saw, the p-value is 0.496, which means the relationship between haemoglobin concentration and height is the same for males and for females.